version: '3'

services:
    app:
        build: .
        container_name: app
        working_dir: /home/www
        ports:
            - "8000:8000"
        volumes:
            - ./:/home/www

    db:
        container_name: db
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: main
        ports:
            - "3306:3306"
